### ISSUE TITLE
Normal logging verbosity is way too verbose when processing XAML

### ISSUE THREAD

**Issue by kzu** [xamarin/Xamarin.Forms#1798]
### Description

When using `Normal` verbosity, we should only issue minimal messages that indicate build progress. We are currently emitting very detailed XAML processing messages when `Normal` verbosity is active, instead of doing so only on `Detailed`.

### Steps to Reproduce

1.  Clone the SmartHotel360 clients repo from https://github.com/Microsoft/SmartHotel360-mobile-desktop-apps
2. Open developer command prompt in the `src` directory
3. Run `msbuild /t:restore SmartHotel.Clients.Android.sln`
4. Run `msbuild SmartHotel.Clients.Android.sln /v:normal`

### Expected Behavior

Only somewhat minimal progress information should be emitted.

### Actual Behavior

We instead get a lot of:

```
_CoreXamlG:
  Source: obj\Debug\netstandard1.4\Views\MyRoomView.xaml
  Language: C#
  AssemblyName: SmartHotel.Clients.Core
  OutputFile obj\Debug\netstandard1.4\SmartHotel.Clients.Core.obj.Debug.netstandard1._4.Views.MyRoomView.xaml.g.cs
```

Followed by another lot of:

```
    Resource: SmartHotel.Clients.Core.obj.Debug.netstandard1._4.App.xaml...
     Creating empty App.__InitComponentRuntime ...done.
     Copying body of InitializeComponent to __InitComponentRuntime ...done.
     Parsing Xaml... done.
     Replacing App.InitializeComponent ()... done.
     Optimizing IL... done
```

### Basic Information

- Version with issue: VS 2017 15.5.6 with the XF version in the given repo.
