### ISSUE TITLE
[Enhancement] Support minified stylesheets

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#2588]
### Description

Minifying stylesheets is a very common practice and helps reduce the size of the bundled resource. It also has a tendency of being very unfriendly to humans. 

### Steps to Reproduce

Have two files:

styles.css

```css
^button: {
  background-color: black;
  color: white;
}
```

styles.min.css

```css
^button:{background-color:black;color:white}
```

Where `styles.min.css` is auto-generated at build and embedded with `styles.css` removed from the EmbeddedResources.

Now when existing StyleSheet references the source as `styles.css`, the app will not be able to load the StyleSheet.
 
```xml
<StyleSheet Source="styles.css" />
```

### Proposal

When loading a CSS Resource it should look for {FileName}.min.css & {FileName}.css. By supporting this directly in Forms it will make it easier for developers to support scenarios where a developer may be conditionally including the human readable stylesheet for Debug builds, and the minified version for Releases.

### Basic Information

- Version with issue: 3.X
- Last known good version: n/a
